# Generated by Django 4.2 on 2023-05-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgBot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['date'], 'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты'},
        ),
        migrations.AlterField(
            model_name='order',
            name='club',
            field=models.CharField(default='Название клуба', max_length=50, verbose_name='Название клуба'),
        ),
    ]
