# Generated by Django 4.2 on 2023-05-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgBot', '0002_alter_order_options_alter_order_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='qr_code',
            field=models.BooleanField(max_length=50, verbose_name='Есть QrCode?'),
        ),
        migrations.AlterField(
            model_name='perfomace',
            name='preview',
            field=models.FileField(default='Превью', upload_to='', verbose_name='Превью'),
        ),
    ]
